// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpAqnfhcI54xbdMdVtH7cyDFzZ_eumalU',
    appId: '1:764111107119:web:ca8f455019a57ccd7d82da',
    messagingSenderId: '764111107119',
    projectId: 'flutter-loginui',
    authDomain: 'flutter-loginui.firebaseapp.com',
    storageBucket: 'flutter-loginui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnjr_5kIOC7aPqOdBr7pybaBbv9uFH_WI',
    appId: '1:764111107119:android:ed01c92fcae0c6647d82da',
    messagingSenderId: '764111107119',
    projectId: 'flutter-loginui',
    storageBucket: 'flutter-loginui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClv62g41ZgI61iCHmFYa_VJQ0K3wnjqkQ',
    appId: '1:764111107119:ios:1e297037e0cd673a7d82da',
    messagingSenderId: '764111107119',
    projectId: 'flutter-loginui',
    storageBucket: 'flutter-loginui.appspot.com',
    iosClientId:
        '764111107119-sev9us9om0k2qa63h9e1hs99qu61t4v1.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );
}
